services:
  - type: web
    name: openschoolsucks
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: "True"
